Repository Metamorn-Team/server, pull requests merged in 2025-04, with the labels that each got.

#21 회원 검색 기능 구현
  prisma/migrations/20250403074747_add_index_nickname_tag_with_id/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/common/pipe/pipe.module.ts
  src/domain/components/users/auth-checker.component.ts
  src/domain/components/users/user-checker.ts
  src/domain/components/users/user-redear.ts
  src/domain/components/users/user-writer.ts
  src/domain/exceptions/enum/domain-exception-type.ts
  src/domain/exceptions/message.ts
  src/domain/interface/user.repository.ts
  src/domain/services/auth/auth.service.ts
  src/domain/services/users/users.service.ts
  src/domain/types/uesr.types.ts
  src/infrastructure/repositories/user-prisma.repository.ts
  src/modules/users/users-component.module.ts
  src/presentation/controller/users/users.controller.ts
  src/presentation/dto/auth/request/register.request.ts
  src/presentation/dto/users/request/search-users.request.ts
  src/presentation/dto/users/response/search-users.response.ts
  test/e2e/user.e2e-spec.ts
Labels: feat 🛠️

#23 zone 소켓 기능 구현 및 로그인 관련 버그 수정
  prisma/schema.prisma
  src/common/decorator/current-user.decorator.ts
  src/common/filter/http-exception.filter.ts
  src/common/guard/ws-auth.guard.ts
  src/domain/interface/storages/game-storage.ts
  src/domain/services/auth/auth.service.ts
  src/domain/services/game/zone.service.ts
  src/domain/types/game.types.ts
  src/infrastructure/storages/memory-storage.ts
  src/main.ts
  src/modules/game/game.module.ts
  src/presentation/controller/users/users.controller.ts
  src/presentation/gateway/game-zone.gateway.ts
  src/presentation/gateway/game.gateway.ts
Labels: feat 🛠️, db 💿

#24 swagger api 작성 및 아바타 키 속성추가
  prisma/migrations/20250403235640_create_friendrequest_model/migration.sql
  prisma/migrations/20250406110739_add_avatar_key_column_in_user/migration.sql
  prisma/schema.prisma
  src/configs/swagger/setup-swagger.ts
  src/domain/entities/user/user.entity.ts
  src/domain/interface/friend.repository.ts
  src/domain/services/auth/auth.service.ts
  src/domain/services/friends/friends.service.ts
  src/domain/types/uesr.types.ts
  src/infrastructure/repositories/friend-prisma.repository.ts
  src/infrastructure/repositories/user-prisma.repository.ts
  src/main.ts
  src/modules/friends/friends-component.module.ts
  src/modules/friends/friends.module.ts
  src/presentation/controller/auth/auth.controller.ts
  src/presentation/controller/friends/friends.controller.ts
  src/presentation/controller/users/users.controller.ts
  src/presentation/dto/auth/request/register.request.ts
  src/presentation/dto/auth/response/login.response.ts
  src/presentation/dto/auth/response/refresh-token.response.ts
  src/presentation/dto/auth/response/register.response.ts
  src/presentation/dto/users/request/change-nickname.request.ts
  src/presentation/dto/users/request/change-tag.request.ts
  src/presentation/dto/users/request/search-users.request.ts
  src/presentation/dto/users/response/get-me.response.ts
  src/presentation/dto/users/response/get-user.response.ts
  src/presentation/dto/users/response/search-users.response.ts
Labels: feat 🛠️

#25 Feat/room
  .gitignore
  src/domain/types/game.types.ts
  src/presentation/dto/auth/index.ts
  src/presentation/dto/auth/request/register.request.ts
  src/presentation/dto/game/index.ts
  src/presentation/dto/game/request/player-join.request.ts
  src/presentation/dto/game/request/player-moved.request.ts
  src/presentation/dto/game/response/active-players.response.ts
  src/presentation/dto/game/response/player-join.response.ts
  src/presentation/dto/game/response/player-left.response.ts
  src/presentation/dto/game/response/player-moved.response.ts
  src/presentation/dto/game/socket/type.ts
  src/presentation/dto/index.ts
  src/presentation/dto/package.json
  src/presentation/dto/shared.ts
  src/presentation/dto/tsconfig.json
  src/presentation/dto/users/index.ts
  src/presentation/dto/users/response/get-me.response.ts
  src/presentation/dto/users/response/get-user.response.ts
  src/presentation/dto/users/response/search-users.response.ts
  src/presentation/gateway/game-zone.gateway.ts
Labels: feat 🛠️

#26 채팅 기능 구현
  src/presentation/dto/game/index.ts
  src/presentation/dto/game/request/send-message.request.ts
  src/presentation/dto/game/response/message-sent.response.ts
  src/presentation/dto/game/response/receive-message.ts
  src/presentation/dto/game/socket/type.ts
  src/presentation/dto/package.json
  src/presentation/gateway/game-zone.gateway.ts
Labels: feat 🛠️

#29 친구 요청 기능 구현
  prisma/migrations/20250409122248_delete_compund_unique_sender_id_and_receiver_id/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/domain/components/friends/friend-checker.ts
  src/domain/components/friends/friend-reader.ts
  src/domain/components/friends/friend-writer.ts
  src/domain/components/users/user-checker.ts
  src/domain/components/users/user-reader.ts
  src/domain/entities/friend/friend.entity.ts
  src/domain/exceptions/enum/domain-exception-type.ts
  src/domain/exceptions/message.ts
  src/domain/interface/friend.repository.ts
  src/domain/services/auth/auth.service.ts
  src/domain/services/friends/friends.service.ts
  src/domain/services/users/users.service.ts
  src/domain/types/friend.types.ts
  src/infrastructure/repositories/friend-prisma.repository.ts
  src/modules/friends/friends-component.module.ts
  src/modules/users/users-component.module.ts
  src/presentation/controller/friends/friends.controller.ts
  src/presentation/controller/users/users.controller.ts
  src/presentation/dto/friends/request/send-friend.request.ts
  src/presentation/gateway/game-zone.gateway.ts
  test/e2e/friend.e2e-spec.ts
  test/e2e/user.e2e-spec.ts
  test/helper/login.ts
Labels: feat 🛠️

#31 섬 관련 데이터 디비 저장 및 이동 로직 구현 방식 변경
  package.json
  prisma/migrations/20250409155356_create_island_and_chat_table/migration.sql
  prisma/migrations/20250409155518_change_snake_case/migration.sql
  prisma/migrations/20250409161202_set_nullable_to_left_at/migration.sql
  prisma/migrations/20250409180113_add_unique_to_island_join/migration.sql
  prisma/migrations/20250409180418_remove_unique_to_island_join/migration.sql
  prisma/schema.prisma
  src/constants/game/attack-box.ts
  src/constants/game/hit-box.ts
  src/constants/threshold.ts
  src/domain/components/chat-message/chat-message-writer.ts
  src/domain/components/island-join/island-join-writer.ts
  src/domain/components/islands/island-writer.ts
  src/domain/entities/chat-messages/chat-message.entity.ts
  src/domain/entities/island-join/island-join.entity.ts
  src/domain/entities/islands/island.entity.ts
  src/domain/interface/chat-message.repository.ts
  src/domain/interface/island-join.repository.ts
  src/domain/interface/island.repository.ts
  src/domain/interface/storages/game-storage.ts
  src/domain/services/chat-messages/chat-message.service.ts
  src/domain/services/game/zone.service.ts
  src/domain/services/island-join/island-join.service.ts
  src/domain/services/islands/island.service.ts
  src/domain/types/game.types.ts
  src/infrastructure/repositories/chat-message-prisma.repository.ts
  src/infrastructure/repositories/island-join-prisma.repository.ts
  src/infrastructure/repositories/island-prisma.repository.ts
  src/infrastructure/storages/memory-storage.ts
  src/modules/chat-messages/chat-message-component.module.ts
  src/modules/chat-messages/chat-message.module.ts
  src/modules/game/game.module.ts
  src/modules/island-joins/island-join-component.module.ts
  src/modules/island-joins/island-join.module.ts
  src/modules/islands/island-component.module.ts
  src/modules/islands/island.module.ts
  src/presentation/dto/game/index.ts
  src/presentation/dto/game/response/attacked.response.ts
  src/presentation/dto/game/response/player-join-success.response.ts
  src/presentation/dto/game/socket/type.ts
  src/presentation/dto/package.json
  src/presentation/gateway/game-zone.gateway.ts
  test/helper/generators.ts
  test/unit/jest.json
  test/unit/services/island-join.service.unit-spec.ts
  test/unit/services/island.service.unit-spec.ts
Labels: feat 🛠️

#32 친구 요청 조회 기능 구현
  package.json
  prisma/migrations/20250414112053_add_relation_friend_request_and_user/migration.sql
  prisma/schema.prisma
  src/domain/components/friends/friend-reader.ts
  src/domain/components/users/user-reader.ts
  src/domain/interface/friend.repository.ts
  src/domain/services/friends/friends.service.ts
  src/domain/types/friend.types.ts
  src/infrastructure/repositories/friend-prisma.repository.ts
  src/modules/friends/friends.module.ts
  src/presentation/controller/friends/friends.controller.ts
  src/presentation/controller/users/users.controller.ts
  src/presentation/dto/friends/index.ts
  src/presentation/dto/friends/request/get-friend-request-list.request.ts
  src/presentation/dto/friends/response/get-friend-request-list.response.ts
  src/presentation/dto/users/request/search-users.request.ts
  test/e2e/app.e2e-spec.ts
  test/e2e/friend.e2e-spec.ts
Labels: feat 🛠️

#33 친구 조회 코멘트 단 부분 수정
  src/domain/components/friends/friend-checker.ts
  src/domain/components/friends/friend-reader.ts
  src/modules/friends/friends-component.module.ts
  src/presentation/controller/friends/friends.controller.ts
  src/presentation/dto/friends/request/send-friend.request.ts
Labels: chore 💩

#35 친구 요청 수락/거절 기능 구현
  src/domain/components/friends/friend-reader.ts
  src/domain/components/friends/friend-writer.ts
  src/domain/interface/friend.repository.ts
  src/domain/services/friends/friends.service.ts
  src/infrastructure/repositories/friend-prisma.repository.ts
  src/presentation/controller/friends/friends.controller.ts
  src/presentation/dto/friends/response/get-friend-request-list.response.ts
  test/e2e/friend.e2e-spec.ts
Labels: feat 🛠️

#39 친구 삭제 기능 구현
  src/domain/components/friends/friend-checker.ts
  src/domain/components/friends/friend-reader.ts
  src/domain/components/friends/friend-writer.ts
  src/domain/interface/friend.repository.ts
  src/domain/services/friends/friends.service.ts
  src/infrastructure/repositories/friend-prisma.repository.ts
  src/presentation/controller/friends/friends.controller.ts
  test/e2e/friend.e2e-spec.ts
Labels: feat 🛠️

#42 친구 목록 조회 기능 구현
  src/domain/components/friends/friend-reader.ts
  src/domain/components/friends/friend-writer.ts
  src/domain/interface/friend.repository.ts
  src/domain/services/friends/friends.service.ts
  src/domain/types/friend.types.ts
  src/infrastructure/repositories/friend-prisma.repository.ts
  src/presentation/controller/friends/friends.controller.ts
  src/presentation/controller/users/users.controller.ts
  src/presentation/dto/friends/index.ts
  src/presentation/dto/friends/request/get-friends.request.ts
  src/presentation/dto/friends/response/get-friends.response.ts
  test/e2e/friend.e2e-spec.ts
Labels: feat 🛠️

#44 회원 검색에 대한 변경사항 수정
  src/domain/components/users/user-reader.ts
  src/domain/exceptions/enum/domain-exception-type.ts
  src/domain/exceptions/message.ts
  src/domain/interface/user.repository.ts
  src/domain/services/users/users.service.ts
  src/infrastructure/repositories/user-prisma.repository.ts
  src/modules/users/users.module.ts
  src/presentation/controller/users/users.controller.ts
  src/presentation/dto/shared.ts
  src/presentation/dto/users/request/search-users.request.ts
  src/presentation/dto/users/response/get-user.response.ts
  test/e2e/user.e2e-spec.ts
Labels: fix 👨🏻‍🔧, refactor 🏠

#45 Feat/player online
  src/domain/interface/storages/game-storage.ts
  src/domain/models/game/player.ts
  src/domain/services/chat-messages/chat-message.service.ts
  src/domain/services/friends/friends.service.ts
  src/domain/services/game/game.service.ts
  src/domain/services/users/users.service.ts
  src/domain/types/game.types.ts
  src/infrastructure/storages/memory-storage.ts
  src/modules/chat-messages/chat-message.module.ts
  src/modules/friends/friends.module.ts
  src/modules/game/game-storage.module.ts
  src/modules/game/game.module.ts
  src/presentation/controller/friends/friends.controller.ts
  src/presentation/dto/friends/response/get-friends.response.ts
  src/presentation/dto/game/index.ts
  src/presentation/dto/game/response/island-heartbeat.ts
  src/presentation/dto/game/socket/type.ts
  src/presentation/dto/package.json
  src/presentation/gateway/island.gateway.ts
  test/e2e/friend.e2e-spec.ts
Labels: feat 🛠️, refactor 🏠

#46 친구 상태 확인 기능 구현
  src/domain/entities/user/user.entity.ts
  src/domain/services/friends/friends.service.ts
  src/domain/types/friend.types.ts
  src/domain/types/uesr.types.ts
  src/presentation/controller/friends/friends.controller.ts
  src/presentation/dto/friends/index.ts
  src/presentation/dto/friends/response/check-friendship.response.ts
  src/presentation/dto/package.json
  src/presentation/dto/shared.ts
  test/e2e/friend.e2e-spec.ts
  test/helper/generators.ts
Labels: feat 🛠️

#47 chore: users, friends api 스웨거 보강
  src/presentation/controller/friends/friends.controller.ts
  src/presentation/controller/users/users.controller.ts
  src/presentation/dto/auth/request/register.request.ts
  src/presentation/dto/friends/response/get-friend-request-list.response.ts
Labels: docs 📜, chore 💩

#48 상품 조회 기능 구현
  package-lock.json
  package.json
  prisma/migrations/20250422110408_create_product_and_category_table/migration.sql
  prisma/migrations/20250422164336_add_description_col_to_product/migration.sql
  prisma/migrations/20250424173055_add_type_and_key_col_to_product/migration.sql
  prisma/migrations/20250424173340_add_not_null_to_type_key_in_product/migration.sql
  prisma/migrations/20250425120317_add_grade_col_to_product/migration.sql
  prisma/migrations/20250425121137_add_gold_col/migration.sql
  prisma/migrations/20250425153050_add_purchase_gold_transcation_table_and_remove_fk/migration.sql
  prisma/migrations/20250425191434_create_item_product_item_table/migration.sql
  prisma/migrations/20250425191911_add_index_to_product_item/migration.sql
  prisma/migrations/20250425192007_add_is_bundle_col_to_product/migration.sql
  prisma/migrations/20250425193824_add_item_id_col_to_product/migration.sql
  prisma/migrations/20250425193915_snake/migration.sql
  prisma/migrations/20250425194012_snake/migration.sql
  prisma/migrations/20250425194324_add_item_index_to_product/migration.sql
  prisma/migrations/20250425200348_remove_product_item_table/migration.sql
  prisma/migrations/20250425202452_remove_category_id/migration.sql
  prisma/migrations/20250425205745_remove_col_toproduct/migration.sql
  prisma/schema.prisma
  src/app.module.ts
  src/configs/cls/cls-config.ts
  src/domain/components/product-categories/product-category-reader.ts
  src/domain/components/products/product-reader.ts
  src/domain/entities/gold-transaction/gold-transaction.entity.ts
  src/domain/entities/item/item.entity.ts
  src/domain/entities/product/product.entity.ts
  src/domain/entities/purchase/purchase.entity.ts
  src/domain/entities/user/user.entity.ts
  src/domain/exceptions/enum/domain-exception-type.ts
  src/domain/interface/gold-transaction.repository.ts
  src/domain/interface/product-category.repository.ts
  src/domain/interface/product.repository.ts
  src/domain/interface/purchase.repository.ts
  src/domain/types/gold-transaction.ts
  src/domain/types/product-category.types.ts
  src/domain/types/product.types.ts
  src/domain/types/purchase.ts
  src/infrastructure/repositories/gold-transaction-prisma.repository.ts
  src/infrastructure/repositories/product-category-prisma.repository.ts
  src/infrastructure/repositories/product-prisma.repository.ts
  src/infrastructure/repositories/purchase-prisma.repository.ts
  src/modules/product-categories/product-category-component.module.ts
  src/modules/product-categories/product-category.module.ts
  src/modules/products/product-component.module.ts
  src/modules/products/product.module.ts
  src/presentation/controller/product-categories/product-category.controller.ts
  src/presentation/controller/products/product.controller.ts
  src/presentation/dto/index.ts
  src/presentation/dto/package.json
  src/presentation/dto/product-categories/index.ts
  src/presentation/dto/product-categories/response/get-all-product-categories.response.ts
  src/presentation/dto/product/index.ts
  src/presentation/dto/product/request/get-product-list.request.ts
  src/presentation/dto/product/response/get-product-list.response.ts
  src/presentation/dto/shared.ts
  test/e2e/product-category.e2e-spec.ts
  test/e2e/product-validation.e2e-spec.ts
  test/e2e/product.e2e-spec.ts
  test/helper/generators.ts
Labels: feat 🛠️
